### ISSUE TITLE
Maximal size of pixmap

### ISSUE THREAD

**Issue by marekhrabe** [adobe-photoshop/generator-core#287]
There is a limit for a dimension in `getPixmap` https://github.com/adobe-photoshop/generator-core/blob/master/lib/jsx/getLayerPixmap.jsx#L51. When the layer exceeds this limit, it gets exported successfully, although pixmap is smaller and bounds are wrong. We found out that increasing this value fixes that problem and it works fine. My question is - does it have any reason why it is maxed at this particular value? And second one - can we increase it?

**Comment by joelrbrandt** [comment]
Well... that _particular_ value isn't precisely important. uncompressed 10000 x 10000 RGB 8-bit images are quite large (280 MB) and the current architecture of generator-core requires that we hold 2 or 3 copies of this in Node's memory (depending on various parameters). When we first architected generator-core, Node v0.10.x was not yet out, and so there wasn't a streaming crypto implementation.

We should (and could) move to a streaming implementation which would _greatly_ improve the memory footprint of the node process (and probably make things faster). But, there's a lot of QE involved in totally swapping out the pixel pipeline for generator, and so it hasn't gotten to the top of the priority queue.

Also, since generator was originally designed to export useable/useful portions of images (e.g. icon assets), it seemed that 10000px was a reasonable upper limit. Yes, there are _definitely_ use cases where we'd like the limit to be higher.

Anyway, that's mostly explanation. How can we get around the problem? Well, in the short term, I would gladly welcome a PR that makes this limit settable in the `generator.getLayerPixmap` call. I'd want it to still default to 10000 pixels, though.

In the long term, streaming is the way to go. I started on it once, and there's actually a branch for this (jrb/streaming). That being said, a.) I don't think that branch will be helpful to anyone, and b.) the hard part is moving it through the "QEing and shipping PS" pipeline moreso than the initial implementation.

Hope that helps!

**Comment by marekhrabe** [comment]
Thanks for the reaction. Yeah… the streaming again… as I said - I can help with the implementation. It's up on you to get it queued in some Photoshop release :) 

I was mostly exporting images where dimension on one axis was particularly small and the other one exceeded the limit, so maybe that was why I didn't even noticed the higher memory usage. Anyway, for now I have created PR #288 for you to review and then it is up to streaming magic :sparkles: to solve this limitation systematically.

**Comment by joelrbrandt** [comment]
Closing as fixed by #288
