### ISSUE TITLE
make "scale" property in savePixmap settings public

### ISSUE THREAD

**Issue by canoztokmak** [adobe-photoshop/generator-core#349]
I'm building a plugin which depends on `scale` property of `savePixmap` function to scale up/down png files. As it is stated on wiki (https://github.com/adobe-photoshop/generator-core/wiki/API-Changes), opening this issue for making that property to be public and stable.

```
     * @param {?number}  settings._scale       A scale factor that causes the image to be resized using convert 
     *    (This API should be considered private and may be removed at any time with only a bump to the "patch"
     *    version number of generator-core. Use at your own risk.)
```

**Comment by mcilroyc** [comment]
I could see how this would be useful, but we are moving towards the use of flitetranscoder (instead of imagemagick) and this option is not supported.  I will include this in a future requirements wishlist document because it makes sense to be able to convert to several different scales of a given pixmap (without having to regenerate a scaled pixmap each time).  Let me know if I am missing some other point @canoztokmak.
